### ISSUE TITLE
Unused field in Points.cs

### ISSUE THREAD

**Issue by leofun01** [lifebeyondfife/Group.Net#1]
File `Group.Net/Points.cs` contain unused private field [`index`](https://github.com/lifebeyondfife/Group.Net/blob/961904e6b3cb7ce4ddca24acdec1cc0494623f47/Group.Net/Points.cs#L12).

**Comment by leofun01** [comment]
[Pull request](../pull/2) was created, so you can just close this issue.

**Comment by lifebeyondfife** [comment]
Closed by PR. Thanks again.
